### ISSUE TITLE
One compartment model did not work on VERTEX 

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/VERTEXShowcase#6]
The Adex2populations_2compartment_model.m ran smoothly, however, when two compartments where replaced with 1 compartment (Adex2populations_1compartment_model.m), model did not run. The error message is : reference to non-existent field 'g_l'. I looked at the source code of the simulator and I assume that this error is due to the fact that g_l (along with other passive properties) is only calculated when NeuronArr(iGroup).numCompartments >1 , instead of >=1 , according to the VERTEX simulator script "calculatePassiveProperties.m". It would be helpful if someone can look at this too, thanks.  

@richardtomsett

**Comment by RokasSt** [comment]
You might look here: 

https://github.com/OpenSourceBrain/VERTEXShowcase/blob/master/VERTEX/Adex2populations_1compartment_model.m

**Comment by richardtomsett** [comment]
Hi - this is correct, g_l is only calculated for multi compartment models, from a provided R_M parameter and the compartment sizes. Single compartment models are meant to have their g_l value specified explicitly, instead of the R_M parameter, as they are not considered to have any size as such. This is a currently undocumented feature though… I'm away at the moment but later this week I'll edit the behaviour of the calculatePassiveProperties code to work for single compartment neurons and add a tutorial for single compartment neurons.

**Comment by RokasSt** [comment]
Hi, thanks for your response
