### ISSUE TITLE
Point neuron is initialized with membrane potential at zero rather than at E_leak

### ISSUE THREAD

**Issue by RokasSt** [OpenSourceBrain/VERTEXShowcase#8]
If we specify the number of compartments to one, your new generated function "generateNeuronModelName.m" produces 'PointNeuronModel_....' . Then the PointNeuronModels are initialized with zeros in contrast to E_leak in NeuronModel.m. I wonder whether this is an error or not, and whether it would be possible that PointNeuronModels also initialize with E_leak as this is typical for most simulations including LEMS-defined ones. Thanks!

@richardtomsett

**Comment by richardtomsett** [comment]
Yeah this is an inconsistency in VERTEX that I hadn't picked up because I never use point neurons other than for poisson inputs/loading previously generated spike times. The point neurons don't initialise v_m to E_leak because it is possible I think to have point neuron models that don't have an E_leak value (poisson spiking neurons for example). I think perhaps to make things consistent I should change the default behaviour of the base NeuronGroup and PointNeuronGroup class constructors to not initialise these values (or initalise to zero), and then the subclasses should be responsible for initialising to the correct starting value (which will usually be E_leak). Will sort this afternoon.

This is really useful by the way as I haven't had anyone else really audit VERTEX's behaviour before, so thank you!

**Comment by richardtomsett** [comment]
OK I've mad the updates in the vertex master branch, see what you think @RokasSt

**Comment by RokasSt** [comment]
No problem, it is also useful for me to read the code of the full application in Matlab such as VERTEX. Moreover, I have to understand most of the parts to be able to replicate results with LEMS descriptions. 

I checked your changes, it is much better right now, I think that to initialize subclasses with the correct starting value is a good idea of yours. Thanks! Have a nice weekend

**Comment by richardtomsett** [comment]
Glad it makes more sense now! I'll close this.
